### ISSUE TITLE
assets/embed.go:10:25: pattern *.min.js: no matching files found

### ISSUE THREAD

**Issue by CarlosLint** [crgimenes/compterm#29]
Cloned the latest version of the repository as of today (12/14/2023)

This is the output after running _go run main.go_:
go: downloading golang.org/x/term v0.15.0
go: downloading golang.org/x/sys v0.15.0
assets/embed.go:10:25: pattern *.min.js: no matching files found

Here's a screenshot for better visualization as well.
![Screenshot from 2023-12-14 01-00-45](https://github.com/crgimenes/compterm/assets/19755656/7b7de430-bf68-495f-bf43-3df1563fefae)

**Comment by crgimenes** [comment]
You need to use the make command.

To generate the production binaries use:

```
make
```

To run in the developer mode use:

```
make dev
```

Don't forget to do a `git pull`, a lot of code is being added/modified daily.

After starting the instance, don't forget to call the API to start the relay. I'm currently doing this via curl, but it will become a command soon.

```
curl -X GET http://localhost:2201/api/action/enable-ws-stream
```
